/**
 * Example Plugin: Code Generator
 *
 * Demonstrates how to create a plugin that adds custom generators
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

import type { Plugin, PluginContext, GeneratorResult } from '../../types/index.js';

export const generatorPlugin: Plugin = {
  capabilities: ['fs:write'],
  name: '@kubit/plugin-generator',
  async onLoad(ctx: PluginContext) {
    ctx.logger.debug('Generator Plugin loaded!');
  },

  /**
   * Register custom generators
   */
  registerGenerators() {
    return [
      {
        description: 'Generate a data model with TypeScript interface and validation',
        generate: async (
          name: string,
          options: { fields?: string[]; validation?: boolean },
          ctx: PluginContext
        ): Promise<GeneratorResult> => {
          try {
            ctx.logger.step(`Generating model: ${name}`);

            const modelDir = join(ctx.cwd, 'src', 'models');
            if (!existsSync(modelDir)) {
              mkdirSync(modelDir, { recursive: true });
            }

            const fields = options.fields || ['id', 'name', 'createdAt'];
            const includeValidation = options.validation !== false;

            // Generate interface
            const interfaceContent = generateModelInterface(name, fields);
            const interfaceFile = join(modelDir, `${name}.ts`);
            writeFileSync(interfaceFile, interfaceContent, 'utf-8');

            const filesCreated = [interfaceFile];

            // Generate validation schema if requested
            if (includeValidation) {
              const validationContent = generateValidationSchema(name, fields);
              const validationFile = join(modelDir, `${name}.schema.ts`);
              writeFileSync(validationFile, validationContent, 'utf-8');
              filesCreated.push(validationFile);
            }

            ctx.logger.success(`Model ${name} generated successfully`);

            return {
              filesCreated,
              message: `Generated model ${name} with ${fields.length} fields`,
              status: 'ok',
            };
          } catch (error) {
            return {
              message: `Failed to generate model: ${(error as Error).message}`,
              status: 'error',
            };
          }
        },
        kind: 'model',
      },
      {
        description: 'Generate a REST API endpoint with controller and routes',
        generate: async (
          name: string,
          options: { methods?: string[] },
          ctx: PluginContext
        ): Promise<GeneratorResult> => {
          try {
            ctx.logger.step(`Generating API endpoint: ${name}`);

            const apiDir = join(ctx.cwd, 'src', 'api');
            if (!existsSync(apiDir)) {
              mkdirSync(apiDir, { recursive: true });
            }

            const methods = options.methods || ['GET', 'POST', 'PUT', 'DELETE'];

            // Generate controller
            const controllerContent = generateController(name, methods);
            const controllerFile = join(apiDir, `${name}.controller.ts`);
            writeFileSync(controllerFile, controllerContent, 'utf-8');

            // Generate routes
            const routesContent = generateRoutes(name, methods);
            const routesFile = join(apiDir, `${name}.routes.ts`);
            writeFileSync(routesFile, routesContent, 'utf-8');

            ctx.logger.success(`API endpoint ${name} generated successfully`);

            return {
              filesCreated: [controllerFile, routesFile],
              message: `Generated API endpoint ${name} with ${methods.length} methods`,
              status: 'ok',
            };
          } catch (error) {
            return {
              message: `Failed to generate API: ${(error as Error).message}`,
              status: 'error',
            };
          }
        },
        kind: 'api',
      },
    ];
  },

  version: '1.0.0',
};

/**
 * Generate TypeScript interface for model
 */
function generateModelInterface(name: string, fields: string[]): string {
  const fieldDefinitions = fields
    .map((field) => {
      // Simple type inference based on field name
      let type = 'string';
      if (field.includes('id') || field.includes('count')) {
        type = 'number';
      }
      if (field.includes('is') || field.includes('has')) {
        type = 'boolean';
      }
      if (field.includes('At') || field.includes('date')) {
        type = 'Date';
      }

      return `  ${field}: ${type};`;
    })
    .join('\n');

  return `/**
 * ${name} Model
 * Auto-generated by @kubit/plugin-generator
 */

export interface ${name} {
${fieldDefinitions}
}

export type ${name}Input = Omit<${name}, 'id' | 'createdAt' | 'updatedAt'>;

export type ${name}Update = Partial<${name}Input>;
`;
}

/**
 * Generate Zod validation schema
 */
function generateValidationSchema(name: string, fields: string[]): string {
  const fieldValidations = fields
    .map((field) => {
      let validation = 'z.string()';
      if (field.includes('id') || field.includes('count')) {
        validation = 'z.number()';
      }
      if (field.includes('is') || field.includes('has')) {
        validation = 'z.boolean()';
      }
      if (field.includes('At') || field.includes('date')) {
        validation = 'z.date()';
      }
      if (field.includes('email')) {
        validation = 'z.string().email()';
      }

      return `  ${field}: ${validation},`;
    })
    .join('\n');

  return `/**
 * ${name} Validation Schema
 * Auto-generated by @kubit/plugin-generator
 */

import { z } from 'zod';

export const ${name}Schema = z.object({
${fieldValidations}
});

export const ${name}InputSchema = ${name}Schema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const ${name}UpdateSchema = ${name}InputSchema.partial();
`;
}

/**
 * Generate controller
 */
function generateController(name: string, methods: string[]): string {
  const methodImplementations = methods
    .map((method) => {
      const methodName = method.toLowerCase();
      return `
  async ${methodName}(req: Request, res: Response) {
    try {
      // TODO: Implement ${method} ${name}
      res.json({ message: '${method} ${name}' });
    } catch (error) {
      res.status(500).json({ error: 'Internal server error' });
    }
  }`;
    })
    .join('\n');

  return `/**
 * ${name} Controller
 * Auto-generated by @kubit/plugin-generator
 */

import type { Request, Response } from 'express';

export class ${name}Controller {${methodImplementations}
}

export const ${name.toLowerCase()}Controller = new ${name}Controller();
`;
}

/**
 * Generate routes
 */
function generateRoutes(name: string, methods: string[]): string {
  const routeDefinitions = methods
    .map((method) => {
      const methodName = method.toLowerCase();
      const path = method === 'GET' ? '/' : method === 'POST' ? '/' : '/:id';
      return `router.${methodName}('${path}', ${name.toLowerCase()}Controller.${methodName});`;
    })
    .join('\n');

  return `/**
 * ${name} Routes
 * Auto-generated by @kubit/plugin-generator
 */

import { Router } from 'express';
import { ${name.toLowerCase()}Controller } from './${name}.controller';

const router = Router();

${routeDefinitions}

export default router;
`;
}

export default generatorPlugin;
